/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EvidenceWallRouteImport } from './routes/evidence-wall'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCasesRouteImport } from './routes/admin/cases'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminKitsRouteImport } from './routes/admin/kits'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStoreRouteImport } from './routes/admin/store'
import { Route as AdminWhatsappRouteImport } from './routes/admin/whatsapp'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AdminCasesCaseIdRouteImport } from './routes/admin/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceWallRoute = EvidenceWallRouteImport.update({
  id: '/evidence-wall',
  path: '/evidence-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/admin/cases',
  path: '/admin/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/admin/contact',
  path: '/admin/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/admin/kits',
  path: '/admin/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/admin/store',
  path: '/admin/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/admin/whatsapp',
  path: '/admin/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesCaseIdRoute = AdminCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AdminCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/cases': typeof CasesRouteWithChildren
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/evidence-wall': typeof EvidenceWallRoute
  '/store': typeof StoreRoute
  '/admin/cases': typeof AdminCasesRouteWithChildren
  '/admin/contact': typeof AdminContactRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/evidence-wall': typeof EvidenceWallRoute
  '/store': typeof StoreRoute
  '/admin/cases': typeof AdminCasesRouteWithChildren
  '/admin/contact': typeof AdminContactRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/cases': typeof CasesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/cases': typeof CasesRouteWithChildren
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/evidence-wall': typeof EvidenceWallRoute
  '/store': typeof StoreRoute
  '/admin/cases': typeof AdminCasesRouteWithChildren
  '/admin/contact': typeof AdminContactRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/cases'
    | '/challenge'
    | '/contact'
    | '/evidence-wall'
    | '/store'
    | '/admin/cases'
    | '/admin/contact'
    | '/admin/inbox'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/whatsapp'
    | '/cases/$caseId'
    | '/orders/$orderId'
    | '/admin/'
    | '/cases/'
    | '/orders/'
    | '/admin/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/challenge'
    | '/contact'
    | '/evidence-wall'
    | '/store'
    | '/admin/cases'
    | '/admin/contact'
    | '/admin/inbox'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/whatsapp'
    | '/cases/$caseId'
    | '/orders/$orderId'
    | '/admin'
    | '/cases'
    | '/orders'
    | '/admin/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/cases'
    | '/challenge'
    | '/contact'
    | '/evidence-wall'
    | '/store'
    | '/admin/cases'
    | '/admin/contact'
    | '/admin/inbox'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/whatsapp'
    | '/cases/$caseId'
    | '/orders/$orderId'
    | '/admin/'
    | '/cases/'
    | '/orders/'
    | '/admin/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CasesRoute: typeof CasesRouteWithChildren
  ChallengeRoute: typeof ChallengeRoute
  ContactRoute: typeof ContactRoute
  EvidenceWallRoute: typeof EvidenceWallRoute
  StoreRoute: typeof StoreRoute
  AdminCasesRoute: typeof AdminCasesRouteWithChildren
  AdminContactRoute: typeof AdminContactRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-wall': {
      id: '/evidence-wall'
      path: '/evidence-wall'
      fullPath: '/evidence-wall'
      preLoaderRoute: typeof EvidenceWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/admin/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/admin/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/admin/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/$caseId': {
      id: '/admin/cases/$caseId'
      path: '/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminCasesCaseIdRouteImport
      parentRoute: typeof AdminCasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface AdminCasesRouteChildren {
  AdminCasesCaseIdRoute: typeof AdminCasesCaseIdRoute
}

const AdminCasesRouteChildren: AdminCasesRouteChildren = {
  AdminCasesCaseIdRoute: AdminCasesCaseIdRoute,
}

const AdminCasesRouteWithChildren = AdminCasesRoute._addFileChildren(
  AdminCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CasesRoute: CasesRouteWithChildren,
  ChallengeRoute: ChallengeRoute,
  ContactRoute: ContactRoute,
  EvidenceWallRoute: EvidenceWallRoute,
  StoreRoute: StoreRoute,
  AdminCasesRoute: AdminCasesRouteWithChildren,
  AdminContactRoute: AdminContactRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
